# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PersonsControl-IOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PersonsControl-IOS
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'Firebase/Crash'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'GoogleSignIn'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'Fabric'
    pod 'Crashlytics'
   
    
  target 'PersonsControl-IOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PersonsControl-IOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
